### ISSUE TITLE
I pull requested to delete one file called "bamboo_shoot.json" in "src\main\resources\assets\adv_agri_core\models"...

### ISSUE THREAD

**Issue by Void7327** [MysteriousStudio/AdvancedAgriculture-core-textures#4]
But I couldn't have found one file related to the file, 
like "tung_oil" is deprecated one for "indus_oil", "bamboo_knife" is deprecated one for "bamboo_chopper"...
Please check if I missed something that I deleted it by mistake.

**Comment by SUIBING112233** [comment]
OK,merged.
